seekur_jr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  #wheel_velocity_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: wheel_joint
  #  pid: {p: 100.0, i: 0.01, d: 10.0}

